CREATE TABLE IF NOT EXISTS `commandes_en_attente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code_commande` VARCHAR(50) NOT NULL,
  `token_paiement` VARCHAR(120) NOT NULL,
  `user_id` INT DEFAULT -1,
  `panier` LONGTEXT NOT NULL,
  `telephone` VARCHAR(30) NOT NULL,
  `paiement_methode` VARCHAR(50) NOT NULL,
  `commentaires` TEXT DEFAULT NULL,
  `lieu_livraison` VARCHAR(255) DEFAULT NULL,
  `secteur` VARCHAR(100) DEFAULT NULL,
  `chambre` VARCHAR(100) DEFAULT NULL,
  `heure_livraison` VARCHAR(50) DEFAULT NULL,
  `montant_total` INT NOT NULL,
  `payment_status` VARCHAR(30) NOT NULL DEFAULT 'pending',
  `payment_url` TEXT DEFAULT NULL,
  `provider_response` LONGTEXT DEFAULT NULL,
  `callback_payload` LONGTEXT DEFAULT NULL,
  `commande_id` INT DEFAULT NULL,
  `confirmed_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_code_commande` (`code_commande`),
  UNIQUE KEY `uniq_token_paiement` (`token_paiement`),
  KEY `idx_payment_status` (`payment_status`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_commande_id` (`commande_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
