<?php

// Fichier de configuration pour les clés API PayDunya
return [
    'PAYDUNYA_MASTER_KEY'  => $_ENV['PAYDUNYA_MASTER_KEY'] ?? getenv('PAYDUNYA_MASTER_KEY') ?: '',
    'PAYDUNYA_PRIVATE_KEY' => $_ENV['PAYDUNYA_PRIVATE_KEY'] ?? getenv('PAYDUNYA_PRIVATE_KEY') ?: '',
    'PAYDUNYA_TOKEN'       => $_ENV['PAYDUNYA_TOKEN'] ?? getenv('PAYDUNYA_TOKEN') ?: '',
    'PAYDUNYA_BASE_URL'    => $_ENV['PAYDUNYA_BASE_URL'] ?? getenv('PAYDUNYA_BASE_URL') ?: '',
    'PAYDUNYA_CHECKOUT_ENDPOINT' => $_ENV['PAYDUNYA_CHECKOUT_ENDPOINT'] ?? getenv('PAYDUNYA_CHECKOUT_ENDPOINT') ?: '',
    'PAYDUNYA_PUBLIC_BASE_URL' => $_ENV['PAYDUNYA_PUBLIC_BASE_URL'] ?? getenv('PAYDUNYA_PUBLIC_BASE_URL') ?: '',
    'PAYDUNYA_CALLBACK_URL' => $_ENV['PAYDUNYA_CALLBACK_URL'] ?? getenv('PAYDUNYA_CALLBACK_URL') ?: '',
    'PAYDUNYA_RETURN_URL' => $_ENV['PAYDUNYA_RETURN_URL'] ?? getenv('PAYDUNYA_RETURN_URL') ?: '',
    'PAYDUNYA_CANCEL_URL' => $_ENV['PAYDUNYA_CANCEL_URL'] ?? getenv('PAYDUNYA_CANCEL_URL') ?: '',
    'PAYDUNYA_AUTH_KEYS' => $_ENV['PAYDUNYA_AUTH_KEYS'] ?? getenv('PAYDUNYA_AUTH_KEYS') ?: '',
    'PAYDUNYA_ALLOWED_HOSTS' => $_ENV['PAYDUNYA_ALLOWED_HOSTS'] ?? getenv('PAYDUNYA_ALLOWED_HOSTS') ?: '',
    'PAYDUNYA_REQUIRE_HTTPS' => $_ENV['PAYDUNYA_REQUIRE_HTTPS'] ?? getenv('PAYDUNYA_REQUIRE_HTTPS') ?: '',
    'PAYDUNYA_PRIVILEGED_ALLOWED_HOSTS' => $_ENV['PAYDUNYA_PRIVILEGED_ALLOWED_HOSTS'] ?? getenv('PAYDUNYA_PRIVILEGED_ALLOWED_HOSTS') ?: '',
    'PAYDUNYA_PRIVILEGED_REQUIRE_HTTPS' => $_ENV['PAYDUNYA_PRIVILEGED_REQUIRE_HTTPS'] ?? getenv('PAYDUNYA_PRIVILEGED_REQUIRE_HTTPS') ?: '',
    'PAYDUNYA_PRIVILEGED_METHODS' => $_ENV['PAYDUNYA_PRIVILEGED_METHODS'] ?? getenv('PAYDUNYA_PRIVILEGED_METHODS') ?: '',
];

?>
